/// Configuration Firebase pour l'application multi-plateforme.
/// Fichier généré automatiquement par la CLI FlutterFire.
/// Pour régénérer: exécutez `flutterfire configure` dans le terminal.
/// Ce fichier centralise les clés API Firebase et configurations spécifiques
/// à chaque plateforme (Web, Android, iOS, macOS, Windows, Linux).
// File generated by flutterfire_cli.
// DO NOT EDIT. This file is auto-generated by Firebase CLI.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb;
import 'package:flutter/material.dart' show TargetPlatform;

/// Classe centralisant les options Firebase pour toutes les plateformes supportées.
/// Permet à Firebase de détecter automatiquement la plateforme d'exécution
/// et d'utiliser la configuration appropriée.
class DefaultFirebaseOptions {
  /// Sélectionne et retourne les options Firebase de la plateforme actuelle.
  /// Détecte automatiquement: Web, Android, iOS, macOS, Windows, Linux.
  /// Lève une exception si la plateforme n'est pas supportée.
  /// Retourne: FirebaseOptions configurées pour la plateforme courante.
  static FirebaseOptions get currentPlatform {
    // Vérifier si l'application s'exécute en tant qu'application Web
    if (kIsWeb) {
      return web;
    }
    // Sinon, basculer selon la plateforme mobile/desktop actuelle
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Configuration Firebase pour la plateforme Web.
  /// Contient les identifiants et clés spécifiques au projet Web.
  /// Projet Firebase: apneafirebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxV9mhFji97ae1fwnF49qO3KJvxvKLzpk',
    appId: '1:1038212712158:web:5e4cac88b0d5e3783f244f',
    messagingSenderId: '1038212712158',
    projectId: 'apneafirebase',
    authDomain: 'apneafirebase.firebaseapp.com',
    storageBucket: 'apneafirebase.firebasestorage.app',
  );

  /// Configuration Firebase pour la plateforme Android.
  /// S'applique à tous les appareils et émulateurs Android.
  /// Inclut l'API key spécifique à Android.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVibnAeKxbQ0MqTQ8_pLyUfYaV0CsC-dU',
    appId: '1:1038212712158:android:47466d1d317df8743f244f',
    messagingSenderId: '1038212712158',
    projectId: 'apneafirebase',
    storageBucket: 'apneafirebase.firebasestorage.app',
  );

  /// Configuration Firebase pour la plateforme iOS.
  /// S'applique aux iPhones et iPads.
  /// Inclut l'API key spécifique à iOS et l'identifiant du bundle iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQwlVWPg8k_NgauCB7GHamoolfe1pLNJI',
    appId: '1:1038212712158:ios:4693de8c1a9079c23f244f',
    messagingSenderId: '1038212712158',
    projectId: 'apneafirebase',
    storageBucket: 'apneafirebase.firebasestorage.app',
    iosBundleId: 'com.example.apneaProject',
  );

  /// Configuration Firebase pour la plateforme macOS.
  /// S'applique aux ordinateurs Apple (macOS).
  /// depuis la console Firebase pour macOS.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY_HERE',
    appId: 'YOUR_MACOS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID.firebaseio.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.example.apneaProject',
  );

  /// Configuration Firebase pour la plateforme Windows.
  /// S'applique aux ordinateurs Windows.
  /// depuis la console Firebase pour Windows.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY_HERE',
    appId: 'YOUR_WINDOWS_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID.firebaseio.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );

  /// Configuration Firebase pour la plateforme Linux.
  /// S'applique aux ordinateurs Linux.
  /// depuis la console Firebase pour Linux.
  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'YOUR_LINUX_API_KEY_HERE',
    appId: 'YOUR_LINUX_APP_ID_HERE',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    databaseURL: 'https://YOUR_PROJECT_ID.firebaseio.com',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
